baseURL = 'https://lensprague.com/stateflowviz/'
languageCode = 'en-us'
title = 'State Flow Mapper'

[params]
  description = 'Visualize how categorical values change over time across one or more logs.'

[markup.goldmark.renderer]
  unsafe = true
